# Generated by Django 2.2 on 2020-08-28 07:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200730_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Колличество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baskets', to='webapp.Product', verbose_name='Товар')),
            ],
        ),
    ]
