# Generated by Django 2.2 on 2020-08-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
